version: '3.8'

services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    env_file: 
      - ./.env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
    networks: 
      - server
  server:
    build: ./server
    ports:
      - '80:80'
    volumes: 
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file: 
      - ./.env
    environment: 
      MONGODB_USERNAME: '${MONGODB_USERNAME}'
      MONGODB_PASSWORD: '${MONGODB_PASSWORD}'
      MONGODB_HOST: '${MONGODB_HOST}'
      MONGODB_NAME: '${MONGODB_NAME}'
      MONGODB_PORT: '${MONGODB_PORT}'
    depends_on:
      - mongodb
    networks: 
      - server
  client:
    build: ./client
    ports: 
      - '3000:3000'
    volumes: 
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - server
    networks: 
      - client
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3007:80"
    networks: 
      - server
      - client

volumes: 
  data:
  logs:

networks: 
  server:
  client: