version: '3.8'

services:
  mongodb:
    image: 'mongo:5.0.3'
    volumes: 
      - ./data:/data/db
    env_file: 
      - ./.env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
    ports: 
      - '${MONGODB_PORT}'
    networks: 
      - server
  server:
    build: ./server
    volumes: 
      - logs:/app/logs #Carefull this volume will set the /app/logs to the root user 
      - ./server:/app
      - /app/node_modules
    env_file: 
      - ./.env
    environment: 
      MONGODB_USERNAME: '${MONGODB_USERNAME}'
      MONGODB_PASSWORD: '${MONGODB_PASSWORD}'
      MONGODB_HOST: '${MONGODB_HOST}'
      MONGODB_NAME: '${MONGODB_NAME}'
      MONGODB_PORT: '${MONGODB_PORT}'
      NODE_PORT: ${NODE_PORT}
    ports:
      - '${SERVER_PORT}:${NODE_PORT}'
    depends_on:
      - mongodb
    networks: 
      - server
  client:
    build: ./client
    ports: 
      - '${CLIENT_PORT}:${REACT_PORT}'
    volumes: 
      - ./client/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on: 
      - server
    networks: 
      - client
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    env_file: 
      - ./.env
    ports:
      - '${APP_PORT}:${NODE_PORT}'
    networks: 
      - server
      - client

volumes: 
  logs:

networks: 
  server:
  client:
