version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: av2
      MONGO_INITDB_ROOT_PASSWORD: secret
  server:
    build: ./server
    ports:
      - '80:80'
    volumes: 
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    environment: 
      MONGODB_USERNAME: av2
      MONGODB_PASSWORD: secret
    depends_on:
      - mongodb
  client:
    build: ./client
    ports: 
      - '3000:3000'
    volumes: 
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - server
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3007:80"

volumes: 
  data:
  logs: